module.exports = {
  Admins: ["UserID", "UserID"],
  ExpressServer: true,
  DefaultPrefix: process.env.Prefix || "?",
  Port: 3000,
  SupportServer: "https://discord.gg/sbySMS7m3v",
  Token: process.env.Token || "",
  ClientID: process.env.Discord_ClientID || "",
  ClientSecret: process.env.Discord_ClientSecret || "",
  Scopes: ["identify", "guilds", "applications.commands"],
  ServerDeafen: true,
  DefaultVolume: 20,
  CallbackURL: "/api/callback", 
  "24/7": false,
  CookieSecret: "Meiw is Cats",
  IconURL:
    "",
  EmbedColor: "RANDOM",
  Permissions: 2205281600,
  Website: process.env.Website || "",
  Presence: {
    status: "idle",
    name: "Meiw",
    type: "WATCHING",
  },
 Lavalink: {
    id: "Main",
    host: process.env.Lavalink_Host || "",
    port: 443,
    pass: process.env.Lavalink_Pass || "",
    secure: true,
    retryAmount: 200,
    retryDelay: 40,
  },
  Spotify: {
    ClientID: process.env.Spotify_ClientID || "",
    ClientSecret: process.env.Spotify_ClientSecret || "",
  },
};
